title: Sankar
author: 
  name: ab-sankar 
  
description: Reflections on a conscious planet

remote_theme: jekyll/minima
minima:
  skin: dark
plugins:
  - jekyll-remote-theme

header_pages:
  - index.md
